#############################################################################
# Makefile for building: main.exe
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  DataStructure.pro
# Template: app
# Command: /home/user/anaconda3/bin/qmake -o Makefile DataStructure.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_LINKED_LIST -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_LINKED_LIST -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -D _X_INLINE=inline -D XK_dead_currency=0xfe6f -D _FORTIFY_SOURCE=2 -D FC_WEIGHT_EXTRABLACK=215 -D FC_WEIGHT_ULTRABLACK=FC_WEIGHT_EXTRABLACK -D GLX_GLXEXT_PROTOTYPES -D_X_INLINE=inline -DXK_dead_currency=0xfe6f -D_FORTIFY_SOURCE=2 -DXK_ISO_Level5_Lock=0xfe13 -DFC_WEIGHT_EXTRABLACK=215 -DFC_WEIGHT_ULTRABLACK=FC_WEIGHT_EXTRABLACK -DGLX_GLXEXT_PROTOTYPES
CFLAGS        = -pipe -Os -fno-exceptions -Wall -Wextra -Wno-expansion-to-defined -fPIC $(DEFINES)
CXXFLAGS      = -pipe -fexceptions -Os -std=gnu++11 -fno-exceptions -Wall -Wextra -Wno-expansion-to-defined -fPIC $(DEFINES)
INCPATH       = -I. -I../../anaconda3/include -I../../anaconda3/mkspecs/linux-g++
QMAKE         = /home/user/anaconda3/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/user/anaconda3/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/user/anaconda3/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = main.exe1.0.0
DISTDIR = /home/user/leetcode/DataStructures/.obj/main.exe1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/user/anaconda3/lib -Wl,-rpath-link,/home/user/anaconda3/lib -L/home/user/anaconda3/lib -Wl,-O1 -Wl,--disable-new-dtags
LIBS          = $(SUBLIBS) -L/home/user/anaconda3/lib -L/opt/conda/conda-bld/qt-main_1660123285207/_build_env/x86_64-conda-linux-gnu/sysroot/usr/lib64 -L/opt/conda/conda-bld/qt-main_1660123285207/_build_env/x86_64-conda-linux-gnu/sysroot/usr/lib   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = .obj/

####### Files

SOURCES       = main.cpp \
		public_functions.cpp 
OBJECTS       = .obj/main.o \
		.obj/public_functions.o
DIST          = ../../anaconda3/mkspecs/features/spec_pre.prf \
		../../anaconda3/mkspecs/common/unix.conf \
		../../anaconda3/mkspecs/common/linux.conf \
		../../anaconda3/mkspecs/common/sanitize.conf \
		../../anaconda3/mkspecs/common/gcc-base.conf \
		../../anaconda3/mkspecs/common/gcc-base-unix.conf \
		../../anaconda3/mkspecs/common/g++-base.conf \
		../../anaconda3/mkspecs/common/g++-unix.conf \
		../../anaconda3/mkspecs/qconfig.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		../../anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_charts.pri \
		../../anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		../../anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_core.pri \
		../../anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		../../anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		../../anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_designer.pri \
		../../anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		../../anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_gui.pri \
		../../anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_help.pri \
		../../anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_input_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_location.pri \
		../../anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		../../anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_network.pri \
		../../anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		../../anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		../../anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		../../anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		../../anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_pdf.pri \
		../../anaconda3/mkspecs/modules/qt_lib_pdf_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		../../anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_positioningquick.pri \
		../../anaconda3/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		../../anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		../../anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qml.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick3d.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick3drender.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		../../anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_script.pri \
		../../anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		../../anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		../../anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		../../anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		../../anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		../../anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_service_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_sql.pri \
		../../anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_svg.pri \
		../../anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		../../anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		../../anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		../../anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		../../anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../anaconda3/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webkit.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webkit_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webview.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_x11extras.pri \
		../../anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_xml.pri \
		../../anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../anaconda3/mkspecs/features/qt_functions.prf \
		../../anaconda3/mkspecs/features/qt_config.prf \
		../../anaconda3/mkspecs/linux-g++/qmake.conf \
		../../anaconda3/mkspecs/features/spec_post.prf \
		../../anaconda3/mkspecs/qmodule.pri \
		../../anaconda3/mkspecs/features/qt_prefix_build_check.prf \
		../../anaconda3/mkspecs/features/qt_build_config.prf \
		../../.qmake.conf \
		../../.qmake.stash \
		../../anaconda3/mkspecs/features/exclusive_builds.prf \
		../../anaconda3/mkspecs/features/toolchain.prf \
		../../anaconda3/mkspecs/features/default_pre.prf \
		../../anaconda3/mkspecs/features/resolve_config.prf \
		../../anaconda3/mkspecs/features/default_post.prf \
		../../anaconda3/mkspecs/features/exceptions_off.prf \
		../../anaconda3/mkspecs/features/qt_example_installs.prf \
		../../anaconda3/mkspecs/features/precompile_header.prf \
		../../anaconda3/mkspecs/features/unix/largefile.prf \
		../../anaconda3/mkspecs/features/warn_on.prf \
		../../anaconda3/mkspecs/features/qmake_use.prf \
		../../anaconda3/mkspecs/features/file_copies.prf \
		../../anaconda3/mkspecs/features/qt_build_extra.prf \
		../../anaconda3/mkspecs/features/qt_docs_targets.prf \
		../../anaconda3/mkspecs/features/testcase_targets.prf \
		../../anaconda3/mkspecs/features/yacc.prf \
		../../anaconda3/mkspecs/features/lex.prf \
		DataStructure.pro linkedlist/*.h \
		stack/*.h \
		tests.h \
		queue/QueueInterface.h \
		public_functions.h \
		queue/DoubleEndedQueue.h \
		queue/ArrayQueue.h \
		vector/vector.h main.cpp \
		public_functions.cpp
QMAKE_TARGET  = main.exe
DESTDIR       = 
TARGET        = main.exe


first: all
####### Build rules

main.exe:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DataStructure.pro ../../.qmake.conf ../../anaconda3/mkspecs/linux-g++/qmake.conf ../../anaconda3/mkspecs/features/spec_pre.prf \
		../../anaconda3/mkspecs/common/unix.conf \
		../../anaconda3/mkspecs/common/linux.conf \
		../../anaconda3/mkspecs/common/sanitize.conf \
		../../anaconda3/mkspecs/common/gcc-base.conf \
		../../anaconda3/mkspecs/common/gcc-base-unix.conf \
		../../anaconda3/mkspecs/common/g++-base.conf \
		../../anaconda3/mkspecs/common/g++-unix.conf \
		../../anaconda3/mkspecs/qconfig.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		../../anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		../../anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_charts.pri \
		../../anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		../../anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_core.pri \
		../../anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		../../anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		../../anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_designer.pri \
		../../anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		../../anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_gui.pri \
		../../anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_help.pri \
		../../anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_input_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_location.pri \
		../../anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		../../anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_network.pri \
		../../anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		../../anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		../../anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		../../anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		../../anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_pdf.pri \
		../../anaconda3/mkspecs/modules/qt_lib_pdf_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		../../anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_positioningquick.pri \
		../../anaconda3/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		../../anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		../../anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qml.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick3d.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick3drender.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		../../anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_script.pri \
		../../anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		../../anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		../../anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		../../anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		../../anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		../../anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_service_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_sql.pri \
		../../anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_svg.pri \
		../../anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		../../anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		../../anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		../../anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		../../anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../anaconda3/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webkit.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webkit_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webview.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_x11extras.pri \
		../../anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_xml.pri \
		../../anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../anaconda3/mkspecs/features/qt_functions.prf \
		../../anaconda3/mkspecs/features/qt_config.prf \
		../../anaconda3/mkspecs/linux-g++/qmake.conf \
		../../anaconda3/mkspecs/features/spec_post.prf \
		../../anaconda3/mkspecs/qmodule.pri \
		../../anaconda3/mkspecs/features/qt_prefix_build_check.prf \
		../../anaconda3/mkspecs/features/qt_build_config.prf \
		../../.qmake.conf \
		../../.qmake.stash \
		../../anaconda3/mkspecs/features/exclusive_builds.prf \
		../../anaconda3/mkspecs/features/toolchain.prf \
		../../anaconda3/mkspecs/features/default_pre.prf \
		../../anaconda3/mkspecs/features/resolve_config.prf \
		../../anaconda3/mkspecs/features/default_post.prf \
		../../anaconda3/mkspecs/features/exceptions_off.prf \
		../../anaconda3/mkspecs/features/qt_example_installs.prf \
		../../anaconda3/mkspecs/features/precompile_header.prf \
		../../anaconda3/mkspecs/features/unix/largefile.prf \
		../../anaconda3/mkspecs/features/warn_on.prf \
		../../anaconda3/mkspecs/features/qmake_use.prf \
		../../anaconda3/mkspecs/features/file_copies.prf \
		../../anaconda3/mkspecs/features/qt_build_extra.prf \
		../../anaconda3/mkspecs/features/qt_docs_targets.prf \
		../../anaconda3/mkspecs/features/testcase_targets.prf \
		../../anaconda3/mkspecs/features/yacc.prf \
		../../anaconda3/mkspecs/features/lex.prf \
		DataStructure.pro
	$(QMAKE) -o Makefile DataStructure.pro
../../anaconda3/mkspecs/features/spec_pre.prf:
../../anaconda3/mkspecs/common/unix.conf:
../../anaconda3/mkspecs/common/linux.conf:
../../anaconda3/mkspecs/common/sanitize.conf:
../../anaconda3/mkspecs/common/gcc-base.conf:
../../anaconda3/mkspecs/common/gcc-base-unix.conf:
../../anaconda3/mkspecs/common/g++-base.conf:
../../anaconda3/mkspecs/common/g++-unix.conf:
../../anaconda3/mkspecs/qconfig.pri:
../../anaconda3/mkspecs/modules/qt_lib_3danimation.pri:
../../anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_3dcore.pri:
../../anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_3dextras.pri:
../../anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_3dinput.pri:
../../anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_3dlogic.pri:
../../anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_3dquick.pri:
../../anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri:
../../anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri:
../../anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri:
../../anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_3drender.pri:
../../anaconda3/mkspecs/modules/qt_lib_3drender_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_bluetooth.pri:
../../anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_charts.pri:
../../anaconda3/mkspecs/modules/qt_lib_charts_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_concurrent.pri:
../../anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_core.pri:
../../anaconda3/mkspecs/modules/qt_lib_core_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_datavisualization.pri:
../../anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_dbus.pri:
../../anaconda3/mkspecs/modules/qt_lib_dbus_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_designer.pri:
../../anaconda3/mkspecs/modules/qt_lib_designer_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_edid_support_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_gamepad.pri:
../../anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_gui.pri:
../../anaconda3/mkspecs/modules/qt_lib_gui_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_help.pri:
../../anaconda3/mkspecs/modules/qt_lib_help_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_input_support_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_kms_support_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_location.pri:
../../anaconda3/mkspecs/modules/qt_lib_location_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_multimedia.pri:
../../anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_network.pri:
../../anaconda3/mkspecs/modules/qt_lib_network_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_networkauth.pri:
../../anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_nfc.pri:
../../anaconda3/mkspecs/modules/qt_lib_nfc_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_opengl.pri:
../../anaconda3/mkspecs/modules/qt_lib_opengl_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_openglextensions.pri:
../../anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_pdf.pri:
../../anaconda3/mkspecs/modules/qt_lib_pdf_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_pdfwidgets.pri:
../../anaconda3/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_positioning.pri:
../../anaconda3/mkspecs/modules/qt_lib_positioning_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_positioningquick.pri:
../../anaconda3/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_printsupport.pri:
../../anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_purchasing.pri:
../../anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_qml.pri:
../../anaconda3/mkspecs/modules/qt_lib_qml_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_qmlmodels.pri:
../../anaconda3/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_qmltest.pri:
../../anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../anaconda3/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_quick.pri:
../../anaconda3/mkspecs/modules/qt_lib_quick3d.pri:
../../anaconda3/mkspecs/modules/qt_lib_quick3d_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../anaconda3/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_quick3drender.pri:
../../anaconda3/mkspecs/modules/qt_lib_quick3drender_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../anaconda3/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_quick3dutils.pri:
../../anaconda3/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_quick_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri:
../../anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri:
../../anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_repparser.pri:
../../anaconda3/mkspecs/modules/qt_lib_repparser_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_script.pri:
../../anaconda3/mkspecs/modules/qt_lib_script_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_scripttools.pri:
../../anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_scxml.pri:
../../anaconda3/mkspecs/modules/qt_lib_scxml_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_sensors.pri:
../../anaconda3/mkspecs/modules/qt_lib_sensors_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_serialbus.pri:
../../anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_serialport.pri:
../../anaconda3/mkspecs/modules/qt_lib_serialport_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_service_support_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_sql.pri:
../../anaconda3/mkspecs/modules/qt_lib_sql_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_svg.pri:
../../anaconda3/mkspecs/modules/qt_lib_svg_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_testlib.pri:
../../anaconda3/mkspecs/modules/qt_lib_testlib_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_texttospeech.pri:
../../anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_uiplugin.pri:
../../anaconda3/mkspecs/modules/qt_lib_uitools.pri:
../../anaconda3/mkspecs/modules/qt_lib_uitools_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../anaconda3/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_webchannel.pri:
../../anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_webengine.pri:
../../anaconda3/mkspecs/modules/qt_lib_webengine_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_webenginecore.pri:
../../anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_webkit.pri:
../../anaconda3/mkspecs/modules/qt_lib_webkit_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../anaconda3/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_websockets.pri:
../../anaconda3/mkspecs/modules/qt_lib_websockets_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_webview.pri:
../../anaconda3/mkspecs/modules/qt_lib_webview_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_widgets.pri:
../../anaconda3/mkspecs/modules/qt_lib_widgets_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_x11extras.pri:
../../anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_xml.pri:
../../anaconda3/mkspecs/modules/qt_lib_xml_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../anaconda3/mkspecs/features/qt_functions.prf:
../../anaconda3/mkspecs/features/qt_config.prf:
../../anaconda3/mkspecs/linux-g++/qmake.conf:
../../anaconda3/mkspecs/features/spec_post.prf:
../../anaconda3/mkspecs/qmodule.pri:
../../anaconda3/mkspecs/features/qt_prefix_build_check.prf:
../../anaconda3/mkspecs/features/qt_build_config.prf:
../../.qmake.conf:
../../.qmake.stash:
../../anaconda3/mkspecs/features/exclusive_builds.prf:
../../anaconda3/mkspecs/features/toolchain.prf:
../../anaconda3/mkspecs/features/default_pre.prf:
../../anaconda3/mkspecs/features/resolve_config.prf:
../../anaconda3/mkspecs/features/default_post.prf:
../../anaconda3/mkspecs/features/exceptions_off.prf:
../../anaconda3/mkspecs/features/qt_example_installs.prf:
../../anaconda3/mkspecs/features/precompile_header.prf:
../../anaconda3/mkspecs/features/unix/largefile.prf:
../../anaconda3/mkspecs/features/warn_on.prf:
../../anaconda3/mkspecs/features/qmake_use.prf:
../../anaconda3/mkspecs/features/file_copies.prf:
../../anaconda3/mkspecs/features/qt_build_extra.prf:
../../anaconda3/mkspecs/features/qt_docs_targets.prf:
../../anaconda3/mkspecs/features/testcase_targets.prf:
../../anaconda3/mkspecs/features/yacc.prf:
../../anaconda3/mkspecs/features/lex.prf:
DataStructure.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile DataStructure.pro

qmake_all: FORCE


all: Makefile main.exe

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

html_docs:
	$(MAKE) -f $(MAKEFILE) prepare_docs && $(MAKE) -f $(MAKEFILE) generate_docs

docs:
	$(MAKE) -f $(MAKEFILE) html_docs && $(MAKE) -f $(MAKEFILE) qch_docs

install_html_docs:

uninstall_html_docs:

install_qch_docs:

uninstall_qch_docs:

install_docs:

uninstall_docs:

qch_docs:

prepare_docs:

generate_docs:

check: first

benchmark: first

compiler_no_pch_compiler_make_all:
compiler_no_pch_compiler_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

.obj/main.o: main.cpp tests.h \
		linkedlist/clinkedlist.h \
		public_functions.h \
		linkedlist/linkedlist.h \
		linkedlist/glinkedlist.h \
		linkedlist/dlinkedlist.h \
		stack/stack.h \
		stack/lstack.h \
		queue/ArrayQueue.h \
		queue/QueueInterface.h \
		queue/DoubleEndedQueue.h \
		vector/vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o main.cpp

.obj/public_functions.o: public_functions.cpp public_functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/public_functions.o public_functions.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

